name: Golf 2015
favicon: null
layout_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose:
  - name: awareness
    item: dd3dd31c-dae5-4aff-a3b9-bce45ac66f76
    url: null
